name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: web-hosting-project-459919

    - name: Build Docker image and push to Artifact Registry
      run: |
        gcloud builds submit --tag gcr.io/web-hosting-project-459919/llm-backend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy llm-backend \
          --image gcr.io/web-hosting-project-459919/llm-backend \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
